baseURL: "https://ste-sangiovanni.github.io" 
title: Stefano Sangiovanni
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
  main:
    - name: Conferences & Talks
      url: talks/
      weight: 2
    - name: Papers
      url: papers/
      weight: 3
    - name: Teaching
      url: teaching/
      weight: 4


params:
    description: ""
    author: Stefano Sangiovanni
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["talks", "papers", "teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
      enabled: true
      title: Stefano Sangiovanni
      subtitle: "I’m a PhD candidate at [**NASP**, University of Milan](https://www.nasp.eu/). Currently, I am visiting the [**Mannheim Centre for European Social Research** (MZES)](https://www.mzes.uni-mannheim.de/). I study how political parties balance positional and valence-based strategies to shape political competition and influence voter perceptions. 
      
       My research focuses on the use of valence strategies by parties across different contexts and their effects on voters. I also analyze the impact of negative valence shocks, such as political scandals. 
        
       I use quantitative and computational methods, including text analysis, survey experiments, and large language models. 
        
       You can read my CV [**here**](https://github.com/ste-sangiovanni/-06--CV/raw/00e4d1b18ac27b6d139c9d1bef0e01891565f799/CV.pdf)."
      imageUrl: "picture.jpeg"
      imageWidth: 160
      imageHeight: 160
      buttons:
        - name: Conferences & Talks
          url: talks/
        - name: Papers
          url: papers/
        - name: Teaching
          url: teaching/
    socialIcons:
        - name: CV
          url: https://github.com/ste-sangiovanni/-06--CV/raw/00e4d1b18ac27b6d139c9d1bef0e01891565f799/CV.pdf
        - name: Email
          url: mailto:stefano.sangiovanni@unimi.it
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/ste-sangiovanni
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
        #  url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Stefano Sangiovanni"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2