baseURL: "https://ste-sangiovanni.github.io" 
title: Stefano Sangiovanni
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
  main:
    - name: CV
      url: https://github.com/ste-sangiovanni/-06--CV/raw/00e4d1b18ac27b6d139c9d1bef0e01891565f799/CV.pdf
      weight: 2
      params:
        target: "_blank"
    - name: Conferences & Talks
      url: talks/
      weight: 3
    - name: Papers
      url: papers/
      weight: 4
    - name: Teaching
      url: teaching/
      weight: 5


params:
    description: "Stefano Sangiovanni's professional website showcasing his research on valence politics, political scandals, and quantitative methods."
    author: Stefano Sangiovanni
    googleAnalyticsID: "G-HL9B2WVWME"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["talks", "papers", "teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
      enabled: true
      title: Stefano Sangiovanni
      subtitle: |
        <p>Hello, this is Stefano! 🌊</p>

        <p>I’m a PhD candidate in Political Science at <a href="https://www.nasp.eu/"><b>NASP, University of Milan</a></b> under the supervision of <a href="https://andreaceron.com/">Prof. Andrea Ceron</a> and <a href="https://giovannainvernizzi.com/">Prof. Giovanna Invernizzi</a>. Currently, I am visiting the <a href="https://www.mzes.uni-mannheim.de/"><b>Mannheim Centre for European Social Research</b></a> (MZES).</p>

        <p>My research focuses on <b>valence politics</b>, analyzing how political parties shape political competition by balancing positional and valence-based strategies in electoral campaigns and parliamentary debates. I also study how negative valence shocks, such as <b>political scandals</b>, affect voter perceptions.</p>

        <p>Methodologically, I use <b>quantitative</b> and <b>computational methods</b>, including text analysis, survey experiments, and large language models.</p>

        <p>Don’t hesitate to reach out if you're interested in connecting, collaborating or discussing research!</p>
      imageUrl: "picture.jpeg"
      imageWidth: 160
      imageHeight: 160
      buttons:
        - name: Conferences & Talks
          url: talks/
        - name: Papers
          url: papers/
        - name: Teaching
          url: teaching/
        - name: CV
          url: https://github.com/ste-sangiovanni/-06--CV/raw/00e4d1b18ac27b6d139c9d1bef0e01891565f799/CV.pdf
    socialIcons:
        - name: CV
          url: https://github.com/ste-sangiovanni/-06--CV/raw/00e4d1b18ac27b6d139c9d1bef0e01891565f799/CV.pdf
        - name: Email
          url: mailto:stefano.sangiovanni@unimi.it
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/ste-sangiovanni
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://x.com/SteSangio
        - name: BlueSky
          url: https://bsky.app/profile/stesangio.bsky.social

    assets:
        disableScrollBarStyle: true
        disalbleHLJS: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Stefano Sangiovanni"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2